services:
    _defaults:
        autowire: true
        autoconfigure: true

#    _instanceof:
#        SmartAssert\WorkerMessageFailedEventBundle\ExceptionHandlerInterface:
#            tags: ['smartassert.worker_message_failed_event_bundle.message_failure_handler.exception_handler']

    SmartAssert\WorkerMessageFailedEventBundle\WorkerMessageFailedEventHandler:
        public: true
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Messenger\Event\WorkerMessageFailedEvent }
        arguments:
            $handlers: !tagged_iterator smartassert.worker_message_failed_event_bundle.message_failure_handler.exception_handler
